### ISSUE TITLE
Incorrect order of images

### ISSUE THREAD

**Issue by dvlasenko96** [lukasz-galka/ngx-gallery#116]
Hello. Could you help me with image ordering, please? I have set 4 columns and 2 rows, and I use 5 images. Why they positioned as 3 - 2 , but not 4 - 1 (screen attached) ? Last image should be in first row and 4th column.
![image](https://user-images.githubusercontent.com/9932072/35948607-065137fa-0c76-11e8-8869-6fd14819a908.png)

**Comment by lukasz-galka** [comment]
Hi @dvlasenko96 gallery by defaut sets images in column order, so
```
1 3 5 X
2 4 X X
```

You can also set row order, but the result will be similar 
```
1 2 3 X
4 5 X X
```

It has to be in this way, because you can have more images than your grid (4x2) can contain. So for example if you have 11 images and grid 4x2 then you will have for column order
```
1 3 5 7 9  11
2 4 6 8 10 X
```

and for row order:
```
1 2 3 4  5  6
7 8 9 10 11 X
```

But of course I understand your problem and I will think about solution - probably on the weekend.

**Comment by helospark** [comment]
Also have the same issue.

In my opinion both could be valid, depending on the usecase. When scrolling is done, then the current ordering could makes more sense, but for example I'm working on a gallery, where all the thumbnails are shown without scrolling, in that case it make sense to fill the first row, then the second row, etc. (it would work similarly to how Column does).

Maybe it could be achieved here:
https://github.com/lukasz-galka/ngx-gallery/blob/master/src/ngx-gallery-thumbnails.component.ts#L173
by using modulo with `this.columns` (instead of `Math.ceil(this.images.length / this.rows)`) and similarly in getThumbnailTop with the division, only if column is specified and the new configuration enabled, otherwise keeping the current behavior.

Regards

**Comment by lukasz-galka** [comment]
I've added new option `NgxGalleryOrder.Page` in `5.8.1`
