### ISSUE TITLE
When clicking an image, the overlay isn't the full height of the screen.

### ISSUE THREAD

**Issue by Rockforced** [lukasz-galka/ngx-gallery#13]
Maybe a possible conflict with angular material?

![bug](https://user-images.githubusercontent.com/27777704/27243052-1eecd530-52ae-11e7-8c8f-27d63759e367.png)

**Comment by lukasz-galka** [comment]
Hi, please take a look at this issue https://github.com/lukasz-galka/ngx-gallery/issues/10

Is your app online or can you create simple demo?

**Comment by lukasz-galka** [comment]
In chrome console you can use this code to find element with `transform `property
`$$("*[style]").filter(el => el.getAttribute('style').indexOf('transform') != -1)`

**Comment by Rockforced** [comment]
Adding these properties to ngx-gallery-active `  height: 100vw;
  width: 100vw;` seemed to fix the issue.

**Comment by Rockforced** [comment]
```
  height: 100vw;
  width: 100vw;

```
Adding these properties to ngx-gallery-active seemed to work, but actually doesn't work well on mobile.

**Comment by lukasz-galka** [comment]
Hi @Rockforced did you find element with transform property or you just add 100vw style? Is this issue resolved or maybe I should reopen this issue?

**Comment by lukasz-galka** [comment]
I have checked material code and this behaviour is because of class `mat-sidenav-content` which has `transform` property. There are two tickets about this issue in material repository https://github.com/angular/material2/issues/4873 and https://github.com/angular/material2/issues/998

At this moment there is one option to fix this behaviour
```
.mat-sidenav-container, .mat-sidenav-content {
    transform: none !important;
}
```
