### ISSUE TITLE
Integration problem

### ISSUE THREAD

**Issue by VictorKozachek** [lukasz-galka/ngx-gallery#136]
Hi,

How to fix that:

Can't bind to 'options' since it isn't a known property of 'ngx-gallery'

?

Thanks

**Comment by lukasz-galka** [comment]
@VictorKozachek pls show me your code

**Comment by DougReynolds** [comment]
Hello, I was awaiting reply with code before posting duplication but see that did not occur.
Here are the related errors:
`Failed: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'ngx-gallery'.
1. If 'ngx-gallery' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ngx-gallery' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        </div>
      </form>
      <ngx-gallery [ERROR ->][options]="galleryOptions" [images]="galleryImages" (change)="onChange($event)"></ngx-gallery>
      "): ng:///DynamicTestModule/HomeContentComponent.html@11:19
Can't bind to 'images' since it isn't a known property of 'ngx-gallery'.
1. If 'ngx-gallery' is an Angular component and it has 'images' input, then verify that it is part of this module.
2. If 'ngx-gallery' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        </div>
      </form>
      <ngx-gallery [options]="galleryOptions" [ERROR ->][images]="galleryImages" (change)="onChange($event)"></ngx-gallery>
      <p>{{getDesicription()}}</p"): ng:///DynamicTestModule/HomeContentComponent.html@11:46
'ngx-gallery' is not a known element:
1. If 'ngx-gallery' is an Angular component, then verify that it is part of this module.
2. If 'ngx-gallery' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </div>
      </form>
      [ERROR ->]<ngx-gallery [options]="galleryOptions" [images]="galleryImages" (change)="onChange($event)"></ngx-ga"): ng:///DynamicTestModule/HomeContentComponent.html@11:6`

It is implemented as such (home-content.component.html):
`<ngx-gallery [options]="galleryOptions" [images]="galleryImages" (change)="onChange($event)"></ngx-gallery>`

(home-content.controller.ts):
`import { Component, OnInit } from '@angular/core';
import { NgxGalleryAnimation, NgxGalleryImage, NgxGalleryOptions} from 'ngx-gallery';
import {Constants} from '../common/constants';
import {ProductService} from './service/product.service';
import {ProductImage} from './service/product_image';

@Component({
  selector: 'app-home-content',
  templateUrl: './home-content.component.html',
  styleUrls: ['./home-content.component.css']
})
export class HomeContentComponent implements OnInit {
  constructor(private productService: ProductService) { }

  galleryOptions: NgxGalleryOptions [];
  galleryImages: NgxGalleryImage [];
.....

this.galleryOptions = [
      {
        width: '100%',
        height: '400px',
        thumbnailsColumns: 4,
        thumbnailsMoveSize: 4,
.......`

**Comment by maurice85** [comment]
anyone?!@!?!? I am facing the same problem

**Comment by madmath03** [comment]
Hello @maurice85,

You should check in which module you imported the `NgxGalleryModule` and in which module your component is.

For instance, let's say you want to use ngx-gallery in `home-content.controller.ts` which is part of a `home.module.ts`.
With that setup, you need to import `NgxGalleryModule` in `home.module.ts`, not `app.module.ts`.
If you import NgxGalleryModule in the AppModule but use the gallery in HomeModule, that's the kind of error you will get.

Hope that helps.

**Comment by mrtabaa** [comment]
> Hello @maurice85,
> 
> You should check in which module you imported the `NgxGalleryModule` and in which module your component is.
> 
> For instance, let's say you want to use ngx-gallery in `home-content.controller.ts` which is part of a `home.module.ts`. With that setup, you need to import `NgxGalleryModule` in `home.module.ts`, not `app.module.ts`. If you import NgxGalleryModule in the AppModule but use the gallery in HomeModule, that's the kind of error you will get.
> 
> Hope that helps.

Thanks man! In my case I have a copmonents.module.ts which all my components are declared there. I had to move **NgxGalleryModule** from app.module.ts to my components module which fixed the issue. You ROCK!
