### ISSUE TITLE
Support for Shortcuts?

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [lukasz-galka/ngx-gallery#22]
Hi, 
this looks like a great project to me, thanks! From documentation I haven't seen the ability to use shortcuts, i.e. ESC for closing the preview image, arrows to navigate through the images (both in normal mode as well as preview mode). 

I'm used to those shortcuts and I believe many end-users as well. It helps to speed up navigation a lot.

**Comment by lukasz-galka** [comment]
Hi @tobi-or-not-tobi there is already option `previewKeyboardNavigation` for keyboard navigation, you can find all available options here https://github.com/lukasz-galka/ngx-gallery#ngxgalleryoptions

I can add option for closing preview by ESC. In my opinion navigation by keyboard in normal mode can be somethimes problematic for end users, but if you need this option I can implement this :)

**Comment by lukasz-galka** [comment]
I have added option `previewCloseOnEsc` in version 1.0.5

I my opinion keyboard navigation for normal mode is tricky because you don't have focus on gallery. For example you can have N galleries and you don't know which gallery should take action on keyboard navigation. The same situation if you have image and thumbnails, keyboard navigation should move image or thumbnails? :)

**Comment by tobi-or-not-tobi** [comment]
Tour ligtning fast, much appreciated. I'll have a look later on the day and give it a go. 

Agreed on this would only work when an element:gallery is focussed. It would still make sense from my pov, but only when there's focus.

**Comment by tobi-or-not-tobi** [comment]
Works like a charm :)
