### ISSUE TITLE
How can I show photos based on base64?

### ISSUE THREAD

**Issue by wilbertjoosen** [lukasz-galka/ngx-gallery#249]

**Comment by paulbanwart** [comment]
Look at the DOM with of an actual image file and you will see that it's setting the the background-image css property on a div element: url(IMAGE_PATH). This is a perfectly fine for base64 encoded images. Simply supply your base64 encoded image instead of IMAGE_PATH in the galleryImages array. It will work. 

Example of a base64 image:
`data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAWwAAABRCAYAAAD2DJx+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAG3SURBVHhe7dbhasIwGEDRdu//zp1jZoNAiE4GXjgHRNumyffr4nkcx3X7/Liu78vz/Hr0ez2s7s/Gutm8/2z1/Nm5Vu+v7PZdeXWO1fp53Wy176PnDbvnw6Pz7eZanTevG1bnDLv3Z7vzh9Ucu/lefT7Mc83Xs9X6YTXHar9htW53f2Web74eHj1v9uz5s7/ON/zXvsPH/RuANyfYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRAh2AARgg0QIdgAEYINECHYABGCDRBxXjf33wC8Mf+wASIEGyBCsAEiBBsg4Tg+ASm0mJnK822AAAAAAElFTkSuQmCC`

**Comment by paulbanwart** [comment]
In other words, a base64 image and a path of the image file are directly substitutable with how this gallery has been architected. All you are doing is supplying a string value.

**Comment by Ruydrigo** [comment]
Hi

I'm trying to use base64 encoded images but it's not working.  When page load in the source I can see:

style="background-image: url(&quot;SafeValue must use [property]=binding: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAwADAAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQ

My code is:

        var sm: SafeResourceUrl = this._sanitizer.bypassSecurityTrustResourceUrl('data:image/jpeg;base64,' + data.pictures[i].picture);

        var a = {
          small: sm,
          medium: sm,
          big: sm,
          description: this.modalRef.content.data.description,
          url: '',
          label: this.modalRef.content.data.description
        }

        this.galleryImages.push(a);

How can I use binding in my case?  Thanks in advance.

**Comment by Ruydrigo** [comment]
I found the answer a few minutes later.  Because of documentation say that support string | SafeResourceUrl I thought that ngx-gallery supported SafeResourceUrl, but instead it support SafeResourceUrl but in string representation (just as paulbanwart wrote)

        var url: SafeResourceUrl = this._sanitizer.bypassSecurityTrustResourceUrl('data:image/jpeg;base64,' + data.fotos[i].foto);

        var url_string = this._sanitizer.sanitize(SecurityContext.RESOURCE_URL, url)!;

        var a = {
           small: url_string,
