### ISSUE TITLE
ngx-gallery not display pictures 

### ISSUE THREAD

**Issue by BlankHrt** [lukasz-galka/ngx-gallery#36]
not display pictures ,but when i click blank ,it can show big picture. i dont know why.here is my code

  
`<ngx-gallery [options]="galleryOptions" [images]="galleryImages"></ngx-gallery>`

`galleryOptions = [
    { 'previewCloseOnEsc': true },
    { 'breakpoint': 500, 'width': '300px', 'height': '300px', 'thumbnailsColumns': 3 },
    { 'breakpoint': 300, 'width': '100%', 'height': '200px', 'thumbnailsColumns': 2 }
  ];`
`galleryImages = [ { big: 'http://192.168.1.108:8080/images/articles/30ef0f2c-092b-448a-a27a.png',medium :'http://192.168.1.108:8080/images/articles/30ef0f2c-092b-448a-a27a-cdcb4ca28ad9.png', small :'http://192.168.1.108:8080/images/articles/30ef0f2c-092b-448a-a27a-cdcb4ca28ad9.png'}];`

**Comment by BlankHrt** [comment]
even not loading
https://www.google.com/images/branding/googlelogo/2x/googlelogo_light_color_272x92dp.png

**Comment by lukasz-galka** [comment]
Hi @BlankHrt you have different images in `big` and dfferent in `small/medium`. That is ok, bu maybe image used in `small/medium` is broken?

I have checked example with https://www.google.com/images/branding/googlelogo/2x/googlelogo_light_color_272x92dp.png and everything is working fine, you can see here (I added black background because white image on white bacjground)
![1](https://user-images.githubusercontent.com/17024927/30103980-959c2ae2-92f4-11e7-9d5a-f38010371d98.jpg)

If you still have problems, please give me more details or create simple demo application.

**Comment by BlankHrt** [comment]
Thank you .It's my problem.

**Comment by talhapro** [comment]
Hi, I am just learning the API and angular, there is an issue while using the ngx-gallery, my photos are not being displayed. I have checked the code multiple time but there is not error I got
